### ISSUE TITLE
Dialog does not properly identify hyperlinks if multiple hyperlinks are present

### ISSUE THREAD

**Issue by korthmat** [yadyn/WPF-Task-Dialog#18]
I have a case where I need to alert the user that a directory copy has failed; I provide links to both the source and destination directories in the message.

Problem is, if I pass in something like this string:

> The job ABC123456A was successfully saved.
> 
> However, an error occurred while attempting to copy its job folder from `<a href="C:\ActiveJobs\ABC123456A">ActiveJobs</a>` to `<a href="C:\ArchiveJobs\ABC123456A">ArchiveJobs</a>`.

...the text I actually get in my message is something like this:
![retry dialog](https://cloud.githubusercontent.com/assets/2089650/3846542/926a213a-1e5d-11e4-8675-72a41be4f2db.png)

The text of the first link never appears, and the link doesn't work at all.

**Comment by yadyn** [comment]
Looks like this only affects the emulated dialog. It's a bug in the regex pattern (isn't it always!) that it uses for capturing hyperlinks for converting into WPF-compatible ones.

It can be easily fixed by modifying the patterns at the top of TaskDialog.cs to the following:

```
private const string HtmlHyperlinkPattern = "<a href=\"[^>]+\">[^<]+<\\/a>";
private const string HtmlHyperlinkCapturePattern = "<a href=\"(?<link>[^>]+)\">(?<text>[^<]+)<\\/a>";
```

This is now fixed in the 2.0 branch.

Thanks for pointing it out!
