### ISSUE TITLE
Add the ability to show a TaskDialog in the taskbar.

### ISSUE THREAD

**Issue by niemyjski** [yadyn/WPF-Task-Dialog#5]
For some dialogs like the progress dialog (just configured TaskDialog options...) which happens when I'm launching my application. It would be nice if you could set a property via the config to show the window in the taskbar.

**Comment by yadyn** [comment]
Looking through the documentation for the native Task Dialog, there does not seem to be a way to make it show in the taskbar. If the native dialog doesn't support it, I won't add it to the emulated one. I agree it would be nice, though.

I believe the reason is that Task Dialogs really are meant to be used with a parent window. If they are taskbar visible, that implies that they are a first-class window for an application, which means they'd need an icon and other stuff, which is generally not the case. I suggest that if you really need this, you might look into creating your own custom dialog to show this progress. You can make it a primary window for your app, then, no problem. Also, if this is important to you anyway, there's a good chance you'll find other things you want to show on it in the future, which the Task Dialog is unlikely to support. Might as well just go ahead and make you a custom one anyway.

**Comment by niemyjski** [comment]
Yeah, I understand (seems like an oversight at MS). 

We have a multithreaded wpf application and we try to do as much as possible during the splash screen / window loading.  I did run into a bug (already logged) where the emulated form ran and was set to the applications main window so I had to move some stuff back into the window load event hehe.
